# Generated by Django 5.2.17 on 2026-09-12 22:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueTurno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modalidad', models.CharField(choices=[('BLOQUE_RESERVADO', 'Bloque Reservado (Scheduled Slot)'), ('CONEXION_LIBRE', 'Conexión Libre (On-Demand)')], default='BLOQUE_RESERVADO', max_length=25)),
                ('franja_horaria', models.CharField(choices=[('DESAYUNO', 'Desayuno (07:00 - 11:00)'), ('ALMUERZO', 'Almuerzo Pico (12:00 - 16:00)'), ('CENA', 'Cena Pico (19:00 - 23:00)'), ('MADRUGADA', 'Madrugada (23:00 - 03:00)'), ('PERSONALIZADA', 'Franja Libre Personalizada')], default='ALMUERZO', max_length=20)),
                ('hora_inicio_programada', models.DateTimeField(blank=True, null=True)),
                ('hora_fin_programada', models.DateTimeField(blank=True, null=True)),
                ('duracion_programada_min', models.PositiveIntegerField(default=120, help_text='Duración en minutos (ej. 60, 120, 180)')),
                ('minuto_progreso', models.PositiveIntegerField(default=0, help_text='Minuto actual en curso del bloque (0 a N)')),
                ('zona_cobertura', models.CharField(default='Centro MTY (Barrio Antiguo)', help_text='Hotspot o zona asignada de inicio', max_length=100)),
                ('estado_turno', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_CURSO', 'En Curso'), ('PAUSADO', 'En Pausa de Descanso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='EN_CURSO', max_length=20)),
                ('estado_conexion', models.CharField(choices=[('DISPONIBLE', 'Disponible / Esperando Órdenes'), ('EN_CAMINO_PICKUP', 'En Camino a Restaurante'), ('EN_ESPERA_RESTAURANTE', 'Esperando Preparación en Local'), ('EN_CAMINO_DELIVERY', 'En Camino a Domicilio de Entrega'), ('EN_PAUSA', 'Pausa Temporal de Conexión'), ('DESCONECTADO', 'Desconectado')], default='DISPONIBLE', max_length=30)),
                ('minutos_pausa_usados', models.PositiveIntegerField(default=0, help_text='Minutos acumulados en pausa (máx 20 min)')),
                ('meta_pedidos_incentivo', models.PositiveIntegerField(default=5, help_text='Meta de entregas para bono de bloque')),
                ('bono_garantizado_mxn', models.DecimalField(decimal_places=2, default=80.0, help_text='Bono garantizado por completar la meta', max_digits=8)),
                ('tasa_aceptacion_pct', models.FloatField(default=100.0, help_text='Tasa de órdenes aceptadas')),
                ('tasa_finalizacion_pct', models.FloatField(default=100.0, help_text='Tasa de entregas completadas con éxito')),
                ('tipo_agente', models.CharField(choices=[('OPTIGO_AI', 'OptiGo AI (Dual-Agent + OR-Tools)'), ('GREEDY', 'Greedy Baseline (Tradicional)')], default='OPTIGO_AI', max_length=20)),
                ('ganancia_neta_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ingresos_brutos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gasto_gasolina_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pedidos_completados', models.PositiveIntegerField(default=0)),
                ('batches_realizados', models.PositiveIntegerField(default=0)),
                ('pedidos_con_retraso', models.PositiveIntegerField(default=0)),
                ('penalizaciones_sla_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('km_totales', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('km_en_vacio', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
