# Generated by Django 5.2.17 on 2026-09-12 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id_externo', models.PositiveIntegerField()),
                ('minuto_aparicion', models.PositiveIntegerField()),
                ('minuto_deadline', models.PositiveIntegerField()),
                ('zona_origen', models.CharField(max_length=100)),
                ('zona_destino', models.CharField(max_length=100)),
                ('solomon_demand', models.PositiveIntegerField(default=1)),
                ('prep_time_min', models.PositiveIntegerField()),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tiempo_viaje_min', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tarifa_base_mxn', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tarifa_final_mxn', models.DecimalField(decimal_places=2, max_digits=8)),
                ('propina_mxn', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='LiquidacionEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto_entrega', models.PositiveIntegerField()),
                ('retraso_minutos', models.IntegerField()),
                ('estado_sla', models.CharField(choices=[('A_TIEMPO', 'A Tiempo'), ('RETRASO_MODERADO', 'Retraso Moderado (>5m - Pérdida Propina)'), ('RETRASO_CRITICO', 'Retraso Crítico (>15m - Multa Tarifa Base)')], max_length=30)),
                ('ingreso_final_mxn', models.DecimalField(decimal_places=2, max_digits=8)),
                ('propina_cobrada_mxn', models.DecimalField(decimal_places=2, max_digits=8)),
                ('penalizacion_sla_mxn', models.DecimalField(decimal_places=2, max_digits=8)),
                ('gasolina_mxn', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ganancia_neta_mxn', models.DecimalField(decimal_places=2, max_digits=8)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='simulation.bloqueturno')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemetry.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoEntornoSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.PositiveIntegerField()),
                ('hora_reloj', models.CharField(max_length=15)),
                ('clima', models.CharField(max_length=100)),
                ('temperatura_c', models.IntegerField()),
                ('factor_trafico', models.FloatField()),
                ('factor_surge', models.FloatField()),
                ('avenida_cerrada', models.CharField(blank=True, max_length=100, null=True)),
                ('zonas_afectadas', models.JSONField(default=list)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_entorno', to='simulation.bloqueturno')),
            ],
            options={
                'ordering': ['minuto'],
                'indexes': [models.Index(fields=['turno', 'minuto'], name='telemetry_e_turno_i_655092_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegistroDecisionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.PositiveIntegerField()),
                ('tipo_agente', models.CharField(default='OPTIGO_AI', max_length=20)),
                ('tipo_accion', models.CharField(max_length=30)),
                ('opcion_id', models.CharField(max_length=50)),
                ('propuesta_estratega', models.JSONField(default=dict)),
                ('dictamen_supervisor', models.JSONField(default=dict)),
                ('log_explicativo', models.TextField()),
                ('pedidos_ids', models.JSONField(default=list)),
                ('ruta_secuencia', models.JSONField(default=list)),
                ('ganancia_neta_proyectada', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tiempo_estimado_min', models.DecimalField(decimal_places=2, max_digits=6)),
                ('distancia_total_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisiones_ia', to='simulation.bloqueturno')),
            ],
            options={
                'ordering': ['minuto'],
                'indexes': [models.Index(fields=['turno', 'minuto'], name='telemetry_r_turno_i_432dbc_idx')],
            },
        ),
    ]
